version = 1

[envs.ruff]
channels = ["conda-forge"]
dependencies = { ruff = "*" }
exposed = { ruff = "ruff" }

[envs.conda-lock]
channels = ["conda-forge"]
dependencies = { conda-lock = "*" }
exposed = { conda-lock = "conda-lock" }

[envs.conda-pack]
channels = ["conda-forge"]
dependencies = { conda-pack = "*" }
exposed = { conda-pack = "conda-pack" }

[envs.grayskull]
channels = ["conda-forge"]
dependencies = { grayskull = "*" }
exposed = { greyskull = "greyskull", grayskull = "grayskull", conda-greyskull = "conda-greyskull", conda-grayskull = "conda-grayskull" }

[envs.conda-build]
channels = ["conda-forge"]
dependencies = { conda-build = "*" }
exposed = { conda-build = "conda-build", conda-debug = "conda-debug", conda-develop = "conda-develop", conda-inspect = "conda-inspect", conda-render = "conda-render", conda-skeleton = "conda-skeleton", conda-convert = "conda-convert", conda-metapackage = "conda-metapackage" }

[envs.speedtest-cli]
channels = ["conda-forge"]
dependencies = { speedtest-cli = "*" }
exposed = { speedtest = "speedtest", speedtest-cli = "speedtest-cli" }

[envs.awscli]
channels = ["conda-forge"]
dependencies = { awscli = "*" }
exposed = { "aws.cmd" = "aws.cmd", aws_bash_completer = "aws_bash_completer", aws = "aws", aws_completer = "aws_completer", aws_zsh_completer = "aws_zsh_completer" }

[envs.taplo]
channels = ["conda-forge"]
dependencies = { taplo = "*" }
exposed = { taplo = "taplo" }

[envs.s-tui]
channels = ["conda-forge"]
dependencies = { s-tui = "*" }
exposed = { s-tui = "s-tui" }

[envs.pixi-pack]
channels = ["conda-forge"]
dependencies = { pixi-pack = "*" }
exposed = { pixi-pack = "pixi-pack" }

[envs.lazygit]
channels = ["conda-forge"]
dependencies = { lazygit = "*" }
exposed = { lazygit = "lazygit" }

[envs.lucky-commit]
channels = ["conda-forge"]
dependencies = { lucky-commit = "*" }
exposed = { lucky_commit = "lucky_commit" }

[envs.go-licenses]
channels = ["conda-forge"]
dependencies = { go-licenses = "*" }
exposed = { go-licenses = "go-licenses" }

[envs.conda-tree]
channels = ["conda-forge"]
dependencies = { conda-tree = "*" }
exposed = { conda-tree = "conda-tree" }

[envs.parquet-tools]
channels = ["conda-forge"]
dependencies = { parquet-tools = "*" }
exposed = { parquet-tools = "parquet-tools" }

[envs.hatch]
channels = ["conda-forge"]
dependencies = { hatch = "*" }
exposed = { hatch = "hatch" }

[envs.television]
channels = ["conda-forge"]
dependencies = { television = "*" }
exposed = { tv = "tv" }

[envs.poetry]
channels = ["conda-forge"]
dependencies = { poetry = "*" }
exposed = { poetry = "poetry" }

[envs.shellcheck]
channels = ["conda-forge"]
dependencies = { shellcheck = "*" }
exposed = { shellcheck = "shellcheck" }

[envs.copier]
channels = ["conda-forge"]
dependencies = { copier = "*" }
exposed = { copier = "copier" }

[envs.bat]
channels = ["conda-forge"]
dependencies = { bat = "*" }
exposed = { bat = "bat" }

[envs.conda-smithy]
channels = ["conda-forge"]
dependencies = { conda-smithy = "*" }
exposed = { feedstocks = "feedstocks", conda-smithy = "conda-smithy" }

[envs.pre-commit]
channels = ["conda-forge"]
dependencies = { pre-commit = "*" }
exposed = { pre-commit = "pre-commit" }

[envs.twine]
channels = ["conda-forge"]
dependencies = { twine = "*" }
exposed = { twine = "twine" }

[envs.chezmoi]
channels = ["conda-forge"]
dependencies = { chezmoi = "*" }
exposed = { chezmoi = "chezmoi" }

[envs.asitop]
channels = ["conda-forge"]
dependencies = { asitop = "*" }
exposed = { asitop = "asitop" }

[envs.cowpy]
channels = ["conda-forge"]
dependencies = { cowpy = "*" }
exposed = { cowpy = "cowpy" }

[envs.conda-deny]
channels = ["conda-forge"]
dependencies = { conda-deny = "*" }
exposed = { conda-deny = "conda-deny" }

[envs.minio-server]
channels = ["conda-forge"]
dependencies = { minio-server = "*" }
exposed = { minio = "minio" }

[envs.git-delta]
channels = ["conda-forge"]
dependencies = { git-delta = "*" }
exposed = { delta = "delta" }

[envs.tokei]
channels = ["conda-forge"]
dependencies = { tokei = "*" }
exposed = { tokei = "tokei" }

[envs.py-crude-resource-monitor]
channels = ["conda-forge"]
dependencies = { py-crude-resource-monitor = "*" }
exposed = { py-crude-resource-monitor = "py-crude-resource-monitor" }

[envs.ripgrep]
channels = ["conda-forge"]
dependencies = { ripgrep = "*" }
exposed = { rg = "rg" }

[envs.fd-find]
channels = ["conda-forge"]
dependencies = { fd-find = "*" }
exposed = { fd = "fd" }

[envs.pixi-diff]
channels = ["conda-forge"]
dependencies = { pixi-diff = "*", pixi-diff-to-markdown = "*" }
exposed = { pixi-diff = "pixi-diff", pixi-diff-to-markdown = "pixi-diff-to-markdown" }
